### ISSUE TITLE
Android4.4端末でセッション開始できない

### ISSUE THREAD

**Issue by kassy-kz** [eaglesakura/andriders-central-engine-v3#91]
セッション開始すると落ちる。
以下ログ

07-24 10:20:45.028 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteLog: (14) cannot open file at line 30185 of [00bb9c9ce4]
07-24 10:20:45.028 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteLog: (14) os_unix.c:30185: (2) open(/storage/sdcard1/andriders/com.eaglesakura.andriders.v3.debug/db/session_log.db) - 
07-24 10:20:45.048 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteDatabase: Failed to open database '/storage/sdcard1/andriders/com.eaglesakura.andriders.v3.debug/db/session_log.db'.
                                                                                        android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                                            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                                            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:977)
                                                                                            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
                                                                                            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
                                                                                            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                                            at com.eaglesakura.android.db.DaoDatabase.open(DaoDatabase.java:66)
                                                                                            at com.eaglesakura.android.db.DaoDatabase.openReadOnly(DaoDatabase.java:94)
                                                                                            at com.eaglesakura.andriders.central.log.SessionLogger.<init>(SessionLogger.java:78)
                                                                                            at com.eaglesakura.andriders.central.CentralDataManager.<init>(CentralDataManager.java:161)
                                                                                            at com.eaglesakura.andriders.service.central.CentralContext.<init>(CentralContext.java:162)
                                                                                            at com.eaglesakura.andriders.service.central.CentralService.onCreate(CentralService.java:57)
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2620)
                                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:212)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
                                                                                            at dalvik.system.NativeStart.main(Native Method)
07-24 10:20:45.048 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteOpenHelper: Couldn't open /storage/sdcard1/andriders/com.eaglesakura.andriders.v3.debug/db/session_log.db for writing (will try read-only):
                                                                                          android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                              at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                                              at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                                              at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                              at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                                              at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                                              at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                              at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:977)
                                                                                              at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
                                                                                              at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
                                                                                              at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                                              at com.eaglesakura.android.db.DaoDatabase.open(DaoDatabase.java:66)
                                                                                              at com.eaglesakura.android.db.DaoDatabase.openReadOnly(DaoDatabase.java:94)
                                                                                              at com.eaglesakura.andriders.central.log.SessionLogger.<init>(SessionLogger.java:78)
                                                                                              at com.eaglesakura.andriders.central.CentralDataManager.<init>(CentralDataManager.java:161)
                                                                                              at com.eaglesakura.andriders.service.central.CentralContext.<init>(CentralContext.java:162)
                                                                                              at com.eaglesakura.andriders.service.central.CentralService.onCreate(CentralService.java:57)
                                                                                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:2620)
                                                                                              at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:212)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
                                                                                              at dalvik.system.NativeStart.main(Native Method)
07-24 10:20:45.048 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteLog: (14) cannot open file at line 30185 of [00bb9c9ce4]
07-24 10:20:45.048 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteLog: (14) os_unix.c:30185: (2) open(/storage/sdcard1/andriders/com.eaglesakura.andriders.v3.debug/db/session_log.db) - 
07-24 10:20:45.058 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/SQLiteDatabase: Failed to open database '/storage/sdcard1/andriders/com.eaglesakura.andriders.v3.debug/db/session_log.db'.
                                                                                        android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                                            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                                            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:235)
                                                                                            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                                            at com.eaglesakura.android.db.DaoDatabase.open(DaoDatabase.java:66)
                                                                                            at com.eaglesakura.android.db.DaoDatabase.openReadOnly(DaoDatabase.java:94)
                                                                                            at com.eaglesakura.andriders.central.log.SessionLogger.<init>(SessionLogger.java:78)
                                                                                            at com.eaglesakura.andriders.central.CentralDataManager.<init>(CentralDataManager.java:161)
                                                                                            at com.eaglesakura.andriders.service.central.CentralContext.<init>(CentralContext.java:162)
                                                                                            at com.eaglesakura.andriders.service.central.CentralService.onCreate(CentralService.java:57)
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2620)
                                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:212)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
                                                                                            at dalvik.system.NativeStart.main(Native Method)
07-24 10:20:45.058 18445-18445/com.eaglesakura.andriders.v3.debug:ace D/AndroidRuntime: Shutting down VM
07-24 10:20:45.058 18445-18445/com.eaglesakura.andriders.v3.debug:ace W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415d3d88)
07-24 10:20:45.058 18445-18445/com.eaglesakura.andriders.v3.debug:ace V/DeployGateUncaughtExceptionHandler: DeployGate caught an exception, trying to send to the service
07-24 10:20:45.068 18445-18445/com.eaglesakura.andriders.v3.debug:ace E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.eaglesakura.andriders.v3.debug:ace, PID: 18445
                                                                                        java.lang.RuntimeException: Unable to create service com.eaglesakura.andriders.service.central.CentralService: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2630)
                                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:212)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
                                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                                         Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                                            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                                            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:235)
                                                                                            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                                            at com.eaglesakura.android.db.DaoDatabase.open(DaoDatabase.java:66)
                                                                                            at com.eaglesakura.android.db.DaoDatabase.openReadOnly(DaoDatabase.java:94)
                                                                                            at com.eaglesakura.andriders.central.log.SessionLogger.<init>(SessionLogger.java:78)
                                                                                            at com.eaglesakura.andriders.central.CentralDataManager.<init>(CentralDataManager.java:161)
                                                                                            at com.eaglesakura.andriders.service.central.CentralContext.<init>(CentralContext.java:162)
                                                                                            at com.eaglesakura.andriders.service.central.CentralService.onCreate(CentralService.java:57)
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2620)
                                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:144) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:212) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5137) 
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718) 
                                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by eaglesakura** [comment]
* 対応中

**Comment by eaglesakura** [comment]
* 解決済み
